{% set version = "1.0.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggparty
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggparty_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggparty/ggparty_{{ version }}.tar.gz
  sha256: c0d1b31e0607c7698242602c22507a231a9c377d342071d774c33dbc28885c74

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-ggplot2
    - r-gtable
    - r-partykit
    - r-rlang
    - r-survival
  run:
    - r-base
    - r-checkmate
    - r-ggplot2
    - r-gtable
    - r-partykit
    - r-rlang
    - r-survival

test:
  commands:
    - $R -e "library('ggparty')"           # [not win]
    - "\"%R%\" -e \"library('ggparty')\""  # [win]

about:
  home: https://github.com/martin-borkovec/ggparty
  license: GPL-2 | GPL-3
  summary: Extends 'ggplot2' functionality to the 'partykit' package. 'ggparty' provides the necessary tools to create clearly structured and highly customizable visualizations for tree-objects of the class 'party'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggparty
# Title: 'ggplot' Visualizations for the 'partykit' Package
# Version: 1.0.0
# Authors@R: c( person("Martin", "Borkovec", role = c("aut", "cre"), email = "martin.borkovec@skyforge.at"),  person("Niyaz", "Madin", role = c("aut"), email = "niyaz.madin@gmail.com"), person("Hadley", "Wickham", role = "ctb"), person("Winston", "Chang", role = "ctb"), person("Lionel", "Henry", role = "ctb"), person("Thomas Lin", "Pedersen", role = "ctb"), person("Kohske", "Takahashi", role = "ctb"), person("Claus", "Wilke", role = "ctb"), person("Kara", "Woo", role = "ctb"), person("Hiroaki", "Yutani", role = "ctb") )
# Copyright: file inst/COPYRIGHTS
# Description: Extends 'ggplot2' functionality to the 'partykit' package. 'ggparty' provides the necessary tools to create clearly structured and highly customizable visualizations for tree-objects of the class 'party'.
# Maintainer: Martin Borkovec <martin.borkovec@skyforge.at>
# Depends: R (>= 3.4.0), ggplot2, partykit
# Imports: grid, gtable, utils, checkmate, methods, survival, rlang
# Suggests: testthat, mlbench, AER, coin, vdiffr, knitr, rmarkdown, pander, MASS, TH.data
# License: GPL-2 | GPL-3
# URL: https://github.com/martin-borkovec/ggparty
# BugReports: https://github.com/martin-borkovec/ggparty/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-15 15:14:50 UTC; Martin
# Author: Martin Borkovec [aut, cre], Niyaz Madin [aut], Hadley Wickham [ctb], Winston Chang [ctb], Lionel Henry [ctb], Thomas Lin Pedersen [ctb], Kohske Takahashi [ctb], Claus Wilke [ctb], Kara Woo [ctb], Hiroaki Yutani [ctb]
# Repository: CRAN
# Date/Publication: 2019-07-18 10:54:06 UTC
